config/routes.rb
Blog::Application.routes.draw do
  get "blog/index"
  get "editors" => "editors/index"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match 'tagged' => 'posts#tagged', :as => 'tagged'
  
  resources :users
  resources :posts

  root :to => 'blog#index', as: 'blog'

end

app/models/post.rb
class Post < ActiveRecord::Base
  # sluggify post tiles
  extend FriendlyId
  friendly_id :title, use: :slugged
  def should_generate_new_friendly_id?
    new_record?
  end
  
  # allow tags on posts
  acts_as_taggable_on :tags
  
  # validation
  STATES = [ "Draft", "Completed", "Published", "Tossed" ]
  SELECTABLE_STATES = [ "All", "Draft", "Completed", "Published", "Tossed" ]
  validates :title, :body, presence: true
  validates :title, uniqueness: true
  validates :state, inclusion: STATES
  
  # store publishing date
  before_validation :check_publish
  
  private
  
    def check_publish
      if self.state == "Published"
        self.published_at = Time.now
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  
  after_destroy :ensure_an_editor_remains
  
  private
    def ensure_an_editor_remains
      if User.count.zero?
        raise "Can't delete last editor"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery

  protected

    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  skip_before_filter :authorize
  
  def index
    @posts = Post.find_all_by_state('Published')
  end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize, only: [:show, :tagged]
  
  # GET /posts
  # GET /posts.json
  def index
    if params[:state] && params[:state] != 'All'
      @posts = Post.where(state: params[:state]).paginate page: params[:page], order: 'created_at desc', per_page: 5
    else
      @posts = Post.paginate page: params[:page], order: 'created_at desc', per_page: 5
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  # Display posts with a specific tag
  def tagged
    if params[:tag].present? 
      @posts = Post.tagged_with(params[:tag]).paginate page: params[:page], order: 'created_at desc', per_page: 5
    else 
      @posts = Post.paginate page: params[:page], order: 'created_at desc', per_page: 5
    end  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to blog_url, notice: "You have successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "Editor #{@user.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
        :autolink => true, :space_after_headers => true, :no_intra_emphasis => true)
    markdown.render(text).html_safe
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog/index.html.erb
<% if notice %>
<p id="home_notice"><%= notice %></p>
<% end %>

<% @posts.each do |post| %>
  <div class="post">
    <h2><%= link_to post.title, post %></h2>
    <div class="pub_date">Published at: <%= post.published_at %></div>
    <div class="post_body"><%= sanitize(render_markdown(post.body)) %></div>
  </div>
<% end %>

app/views/editors/index.html.erb
<div id="content">
  <h1>Editors#index</h1>
  <p>Find me in app/views/editors/index.html.erb</p>
</div><!-- eof content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

  <div id="wrapper">
    <div id="header">
      <h1>&#91;&nbsp;freebl&#246;g&nbsp;&#93;</h1>
    </div><!-- eof header -->
    
    <div id="leftcol">
      <ul id="nav">
        <li><%= link_to 'Blog Home', blog_path %></li>
        <% if session[:user_id] %>
        <li><%= link_to 'Manage Posts', posts_path %></li>
        <li><%= link_to 'Manage Editors', users_path %></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Editor Login', login_path %></li>
        <% end %>
      </ul>
    </div><!-- eof leftcol -->
    
    <div id="rightcol">
      <%= yield %>
    </div><!-- eof rightcol -->
  </div>

  <div id="footer">
    <div id="footer_text">Thanks for visiting.</div>
  </div><!-- eof footer -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.select :state, Post::STATES, prompt: 'Select a post state' %>
  </div>
  
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tag_list %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="content">

  <h1>Editing post</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>

</div><!-- eof content -->

app/views/posts/index.html.erb
<div id="posts">

  <h1>Listing posts</h1>

  <%= form_tag(posts_path, :method => 'get', :id => 'state_form') do %>
    <label>State:</label>
    <%= select_tag(:state, options_for_select(Post::SELECTABLE_STATES), :id=>'select_state', :prompt=>'Select a Post State') %>
  <% end %>

  <script type="text/javascript">
  $(window).bind("load", function() {
    $('#select_state').change(function(){
        $('#state_form').submit();
    });
  });
  </script>

  <table>
    <tr>
      <th>Title</th>
      <th>State</th>
      <th>Slug</th>
      <th>Published at</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.state %></td>
      <td><%= post.slug %></td>
      <td><%= post.published_at %></td>
      <td>
        <% post.tags.any? %>
          <% post.tags.each do |tag| %>
          <%= link_to tag.name, tagged_url(:tag => tag.name) %>
        <% end %>
      </td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Delete', post, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Post', new_post_path %>
  <p><%= will_paginate @posts %></p>
  
</div><!-- eof posts -->

app/views/posts/new.html.erb
<div id="content">

  <h1>New post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>

</div><!-- eof content -->

app/views/posts/show.html.erb
<div id="content">

  <p id="notice"><%= notice %></p>

  <h2>
    <%= @post.title %>
  </h2>

  <br />
  <p>
    <b>Published at:</b>
    <%= @post.published_at %>
  </p>

  <p>
    <%= sanitize(render_markdown(@post.body)) %>
  </p>

  <p>
    <% @post.tags.any? %>
      Tags: 
      <% @post.tags.each do |tag| %>
      <%= link_to tag.name, tagged_url(:tag => tag.name) %>
    <% end %>
  </p>

  <% if session[:user_id] %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <% end %>
  <% if session[:user_id] %>
  <%= link_to 'Back', posts_path %>
  <% else %>
  <%= link_to 'Back', blog_path %>
  <% end %>

</div><!-- eof content -->

app/views/posts/tagged.html.erb
<div id="posts">

  <h1>Listing posts</h1>

  <table>
    <tr>
      <th>Title</th>
      <th>State</th>
      <th>Slug</th>
      <th>Published at</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= sanitize(post.title) %></td>
      <td><%= post.state %></td>
      <td><%= post.slug %></td>
      <td><%= post.published_at %></td>
      <td>
        <% post.tags.any? %>
          <% post.tags.each do |tag| %>
          <%= link_to tag.name, tagged_url(:tag => tag.name) %>
        <% end %>
      </td>
      <td><%= link_to 'Show', post %></td>
      <td><% if session[:user_id] %><%= link_to 'Edit', edit_post_path(post) %><% end %></td>
      <td><% if session[:user_id] %><%= link_to 'Delete', post, confirm: 'Are you sure?', method: :delete %><% end %></td>
    </tr>
  <% end %>
  </table>

  <br />
  
  <% if session[:user_id] %>
  <%= link_to 'New Post', new_post_path %>
  <% end %>
  
  <p><%= will_paginate @posts %></p>
  
</div><!-- eof posts -->

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>

  <div>
    <%= f.label :name %>:
    <%= f.text_field :name, size: 20 %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>:
    <%= f.password_field :password, size: 20 %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm' %>:
    <%= f.password_field :password_confirmation, size: 20 %>
  </div>

  <div>
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/edit.html.erb
<div id="content">
  <h1>Editing user</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div><!-- eof content -->

app/views/users/index.html.erb
<div id="content">
  <h1>Listing users</h1>
  <% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>

  <table>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New User', new_user_path %>
</div><!-- eof content -->

app/views/users/new.html.erb
<div id="content">
  <h1>New user</h1>
  <%= render 'form' %>
  <%= link_to 'Back', users_path %>
</div><!-- eof content -->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>